spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.show_sql: true
    hibernate:
      ddl-auto: none